package io.github.spec2test.generator

import io.github.spec2test.ir.*

/**
 * Generates JUnit 5 test classes from a [TlaModule].
 *
 * Supports three test generation strategies:
 *   1. [GenerationMode.SEQUENTIAL] — Random-walk state machine exploration
 *   2. [GenerationMode.CONCURRENT] — Multi-threaded harness with invariant checks
 *   3. [GenerationMode.TRACE_GUIDED] — TLC-derived deterministic test scenarios
 */
class JavaTestGenerator {

    data class Config(
        val packageName: String = "io.github.spec2test.generated",
        val mode: GenerationMode = GenerationMode.SEQUENTIAL,
        val threads: Int = 3,
        val stepsPerTest: Int = 100,
        val numRandomTests: Int = 50,
        val embedInvariants: Boolean = true,
        val generateHelperComments: Boolean = true
    )

    enum class GenerationMode { SEQUENTIAL, CONCURRENT, TRACE_GUIDED }

    data class GeneratedTest(
        val className: String,
        val packageName: String,
        val code: String,
        val mode: GenerationMode
    )

    // ─── PUBLIC API ──────────────────────────────────────────────────────

    fun generate(module: TlaModule, config: Config): List<GeneratedTest> {
        val results = mutableListOf<GeneratedTest>()

        if (config.mode == GenerationMode.SEQUENTIAL || config.mode == GenerationMode.CONCURRENT) {
            results.add(generateSequentialTest(module, config))
        }
        if (config.mode == GenerationMode.CONCURRENT) {
            results.add(generateConcurrentTest(module, config))
        }

        return results
    }

    // ─── SEQUENTIAL TEST GENERATION ──────────────────────────────────────

    private fun generateSequentialTest(module: TlaModule, config: Config): GeneratedTest {
        val className = "${module.name}SequentialTest"
        val translator = buildTranslator(module)
        val actions = module.actions
        val invariants = module.invariants
        val init = module.init

        val sb = StringBuilder()

        // Package & imports
        sb.appendLine("package ${config.packageName};")
        sb.appendLine()
        sb.appendLine("import org.junit.jupiter.api.Test;")
        sb.appendLine("import org.junit.jupiter.api.BeforeEach;")
        sb.appendLine("import org.junit.jupiter.api.RepeatedTest;")
        sb.appendLine("import static org.junit.jupiter.api.Assertions.*;")
        sb.appendLine()
        sb.appendLine("import java.util.*;")
        sb.appendLine("import java.util.stream.*;")
        sb.appendLine("import java.util.concurrent.ThreadLocalRandom;")
        sb.appendLine()

        // Class javadoc
        sb.appendLine("/**")
        sb.appendLine(" * Sequential conformance test generated from TLA+ specification: ${module.name}")
        sb.appendLine(" *")
        sb.appendLine(" * This test models the TLA+ state machine and explores random action sequences,")
        sb.appendLine(" * verifying that all safety invariants hold after every state transition.")
        sb.appendLine(" *")
        sb.appendLine(" * Generated by spec2test — TLA+ to Java Test Generator")
        sb.appendLine(" *")
        sb.appendLine(" * Formal foundation:")
        sb.appendLine(" *   LTS = (S, S₀, Σ, →, Φ) where")
        sb.appendLine(" *     S  = {${module.variables.joinToString(", ") { it.name }}}")
        sb.appendLine(" *     Σ  = {${actions.joinToString(", ") { it.name }}}")
        sb.appendLine(" *     Φ  = {${invariants.joinToString(", ") { it.name }}}")
        sb.appendLine(" */")
        sb.appendLine("public class $className {")
        sb.appendLine()

        // State variables
        sb.appendLine("    // ── State Space S ──────────────────────────────────────────────")
        for (v in module.variables) {
            val javaType = JavaExprTranslator.typeToJava(v.type)
            sb.appendLine("    private $javaType ${v.name};")
        }
        sb.appendLine()

        // Constants
        if (module.constants.isNotEmpty()) {
            sb.appendLine("    // ── Constants ─────────────────────────────────────────────────")
            for (c in module.constants) {
                val javaType = JavaExprTranslator.typeToJava(c.type)
                val defaultVal = guessConstantDefault(c, module)
                sb.appendLine("    private static final $javaType ${c.name} = $defaultVal;")
            }
            sb.appendLine()
        }

        // Init
        sb.appendLine("    // ── Initial State S₀ ──────────────────────────────────────────")
        sb.appendLine("    @BeforeEach")
        sb.appendLine("    void init() {")
        if (init != null) {
            val initAssignments = extractInitAssignments(init.body, translator)
            for ((varName, expr) in initAssignments) {
                val varType = module.variables.find { it.name == varName }?.type
                if (varType != null && isCollectionType(varType)) {
                    sb.appendLine("        this.$varName = new ${JavaExprTranslator.typeToMutableJava(varType)}($expr);")
                } else {
                    sb.appendLine("        this.$varName = $expr;")
                }
            }
        }
        sb.appendLine("    }")
        sb.appendLine()

        // Action methods
        sb.appendLine("    // ── Actions Σ ─────────────────────────────────────────────────")
        for (action in actions) {
            generateActionMethod(sb, action, module, translator, config)
        }

        // Invariant checker
        if (config.embedInvariants && invariants.isNotEmpty()) {
            sb.appendLine("    // ── Safety Invariants Φ ───────────────────────────────────────")
            sb.appendLine("    private void checkInvariants() {")
            for (inv in invariants) {
                val javaExpr = translator.translateExpr(inv.body)
                sb.appendLine("        if (!($javaExpr)) {")
                sb.appendLine("            fail(\"Invariant '${inv.name}' violated: ${escapeJavaString(inv.rawTla.take(100))}\");")
                sb.appendLine("        }")
            }
            sb.appendLine("    }")
            sb.appendLine()
        }

        // Random walk test
        sb.appendLine("    // ── Test: Random Walk State Exploration ────────────────────────")
        sb.appendLine("    @RepeatedTest(${config.numRandomTests})")
        sb.appendLine("    void randomWalkTest() {")
        sb.appendLine("        var rng = ThreadLocalRandom.current();")
        sb.appendLine("        for (int step = 0; step < ${config.stepsPerTest}; step++) {")
        sb.appendLine("            int action = rng.nextInt(${actions.size});")
        sb.appendLine("            switch (action) {")
        for ((i, action) in actions.withIndex()) {
            val paramArgs = generateRandomParams(action, module)
            sb.appendLine("                case $i -> ${action.name}($paramArgs);")
        }
        sb.appendLine("            }")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine()

        // Bounded enumeration test (for small action spaces)
        if (actions.size <= 5) {
            sb.appendLine("    // ── Test: Bounded Enumeration (depth ${minOf(4, config.stepsPerTest)}) ─────────────────")
            sb.appendLine("    @Test")
            sb.appendLine("    void boundedEnumerationTest() {")
            sb.appendLine("        enumerateActions(${minOf(4, config.stepsPerTest)});")
            sb.appendLine("    }")
            sb.appendLine()
            sb.appendLine("    private void enumerateActions(int depth) {")
            sb.appendLine("        if (depth <= 0) return;")
            sb.appendLine("        for (int action = 0; action < ${actions.size}; action++) {")

            // Save state
            for (v in module.variables) {
                val javaType = JavaExprTranslator.typeToJava(v.type)
                if (isCollectionType(v.type)) {
                    sb.appendLine("            var saved_${v.name} = new ${JavaExprTranslator.typeToMutableJava(v.type)}(${v.name});")
                } else {
                    sb.appendLine("            var saved_${v.name} = ${v.name};")
                }
            }

            sb.appendLine("            switch (action) {")
            for ((i, action) in actions.withIndex()) {
                val defaultParams = generateDefaultParams(action)
                sb.appendLine("                case $i -> ${action.name}($defaultParams);")
            }
            sb.appendLine("            }")
            sb.appendLine("            enumerateActions(depth - 1);")

            // Restore state
            for (v in module.variables) {
                sb.appendLine("            ${v.name} = saved_${v.name};")
            }

            sb.appendLine("        }")
            sb.appendLine("    }")
            sb.appendLine()
        }

        sb.appendLine("}")
        sb.appendLine()

        return GeneratedTest(className, config.packageName, sb.toString(), GenerationMode.SEQUENTIAL)
    }

    // ─── CONCURRENT TEST GENERATION ──────────────────────────────────────

    private fun generateConcurrentTest(module: TlaModule, config: Config): GeneratedTest {
        val className = "${module.name}ConcurrentTest"
        val translator = buildTranslator(module)
        val actions = module.actions
        val invariants = module.invariants
        val init = module.init

        val sb = StringBuilder()

        sb.appendLine("package ${config.packageName};")
        sb.appendLine()
        sb.appendLine("import org.junit.jupiter.api.Test;")
        sb.appendLine("import org.junit.jupiter.api.BeforeEach;")
        sb.appendLine("import org.junit.jupiter.api.RepeatedTest;")
        sb.appendLine("import static org.junit.jupiter.api.Assertions.*;")
        sb.appendLine()
        sb.appendLine("import java.util.*;")
        sb.appendLine("import java.util.concurrent.*;")
        sb.appendLine("import java.util.concurrent.atomic.*;")
        sb.appendLine("import java.util.stream.*;")
        sb.appendLine()
        sb.appendLine("/**")
        sb.appendLine(" * Concurrent harness test generated from TLA+ specification: ${module.name}")
        sb.appendLine(" *")
        sb.appendLine(" * Executes actions concurrently across ${config.threads} threads with")
        sb.appendLine(" * barrier-based phased execution:")
        sb.appendLine(" *   1. Concurrent phase: all threads execute random actions")
        sb.appendLine(" *   2. Quiescence: all threads reach barrier → invariant check")
        sb.appendLine(" *   3. Repeat for ${config.stepsPerTest} phases")
        sb.appendLine(" *")
        sb.appendLine(" * Each action is wrapped in synchronized(lock) to model TLA+ atomic transitions.")
        sb.appendLine(" * If any interleaving produces a state violating an invariant, the test fails")
        sb.appendLine(" * with a diagnostic trace.")
        sb.appendLine(" *")
        sb.appendLine(" * Generated by spec2test — TLA+ to Java Test Generator")
        sb.appendLine(" */")
        sb.appendLine("public class $className {")
        sb.appendLine()

        // Lock object
        sb.appendLine("    private final Object lock = new Object();")
        sb.appendLine("    private final List<String> trace = Collections.synchronizedList(new ArrayList<>());")
        sb.appendLine()

        // State variables
        sb.appendLine("    // ── State Space S ──────────────────────────────────────────────")
        for (v in module.variables) {
            val javaType = JavaExprTranslator.typeToJava(v.type)
            sb.appendLine("    private volatile $javaType ${v.name};")
        }
        sb.appendLine()

        // Constants
        if (module.constants.isNotEmpty()) {
            sb.appendLine("    // ── Constants ─────────────────────────────────────────────────")
            for (c in module.constants) {
                val javaType = JavaExprTranslator.typeToJava(c.type)
                val defaultVal = guessConstantDefault(c, module)
                sb.appendLine("    private static final $javaType ${c.name} = $defaultVal;")
            }
            sb.appendLine()
        }

        // Init
        sb.appendLine("    @BeforeEach")
        sb.appendLine("    void init() {")
        sb.appendLine("        trace.clear();")
        if (init != null) {
            val initAssignments = extractInitAssignments(init.body, translator)
            for ((varName, expr) in initAssignments) {
                val varType = module.variables.find { it.name == varName }?.type
                if (varType != null && isCollectionType(varType)) {
                    sb.appendLine("        this.$varName = new ${JavaExprTranslator.typeToMutableJava(varType)}($expr);")
                } else {
                    sb.appendLine("        this.$varName = $expr;")
                }
            }
        }
        sb.appendLine("    }")
        sb.appendLine()

        // Action methods (synchronized)
        sb.appendLine("    // ── Actions Σ (synchronized — models TLA+ atomicity) ──────────")
        for (action in actions) {
            generateSynchronizedActionMethod(sb, action, module, translator, config)
        }

        // Invariant checker
        if (config.embedInvariants && invariants.isNotEmpty()) {
            sb.appendLine("    // ── Safety Invariants Φ ───────────────────────────────────────")
            sb.appendLine("    private void checkInvariants() {")
            for (inv in invariants) {
                val javaExpr = translator.translateExpr(inv.body)
                sb.appendLine("        if (!($javaExpr)) {")
                sb.appendLine("            fail(\"Invariant '${inv.name}' violated.\\nTrace: \" + String.join(\" -> \", trace));")
                sb.appendLine("        }")
            }
            sb.appendLine("    }")
            sb.appendLine()
        }

        // Concurrent test
        sb.appendLine("    // ── Test: Concurrent Execution with Phased Invariant Checks ───")
        sb.appendLine("    @RepeatedTest(10)")
        sb.appendLine("    void concurrentPhasedTest() throws Exception {")
        sb.appendLine("        int numThreads = ${config.threads};")
        sb.appendLine("        int phases = ${config.stepsPerTest / config.threads};")
        sb.appendLine("        var barrier = new CyclicBarrier(numThreads + 1); // +1 for checker")
        sb.appendLine("        var errors = new CopyOnWriteArrayList<Throwable>();")
        sb.appendLine()
        sb.appendLine("        var executor = Executors.newFixedThreadPool(numThreads);")
        sb.appendLine("        for (int t = 0; t < numThreads; t++) {")
        sb.appendLine("            executor.submit(() -> {")
        sb.appendLine("                try {")
        sb.appendLine("                    var rng = ThreadLocalRandom.current();")
        sb.appendLine("                    for (int phase = 0; phase < phases; phase++) {")
        sb.appendLine("                        // Execute random action")
        sb.appendLine("                        int action = rng.nextInt(${actions.size});")
        sb.appendLine("                        switch (action) {")
        for ((i, action) in actions.withIndex()) {
            val paramArgs = generateRandomParams(action, module)
            sb.appendLine("                            case $i -> ${action.name}($paramArgs);")
        }
        sb.appendLine("                        }")
        sb.appendLine("                        barrier.await(5, TimeUnit.SECONDS);")
        sb.appendLine("                    }")
        sb.appendLine("                } catch (Throwable e) {")
        sb.appendLine("                    errors.add(e);")
        sb.appendLine("                }")
        sb.appendLine("            });")
        sb.appendLine("        }")
        sb.appendLine()
        sb.appendLine("        // Checker thread: verify invariants at each phase boundary")
        sb.appendLine("        for (int phase = 0; phase < phases; phase++) {")
        sb.appendLine("            barrier.await(5, TimeUnit.SECONDS);")
        sb.appendLine("            synchronized (lock) {")
        sb.appendLine("                checkInvariants();")
        sb.appendLine("            }")
        sb.appendLine("        }")
        sb.appendLine()
        sb.appendLine("        executor.shutdown();")
        sb.appendLine("        assertTrue(executor.awaitTermination(30, TimeUnit.SECONDS), \"Timeout\");")
        sb.appendLine("        if (!errors.isEmpty()) {")
        sb.appendLine("            throw new AssertionError(\"Thread error: \" + errors.getFirst().getMessage(), errors.getFirst());")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine()

        // Simple concurrent stress test
        sb.appendLine("    // ── Test: Concurrent Stress (no phasing) ──────────────────────")
        sb.appendLine("    @RepeatedTest(5)")
        sb.appendLine("    void concurrentStressTest() throws Exception {")
        sb.appendLine("        int numThreads = ${config.threads};")
        sb.appendLine("        int opsPerThread = ${config.stepsPerTest};")
        sb.appendLine("        var latch = new CountDownLatch(numThreads);")
        sb.appendLine("        var errors = new CopyOnWriteArrayList<Throwable>();")
        sb.appendLine()
        sb.appendLine("        for (int t = 0; t < numThreads; t++) {")
        sb.appendLine("            new Thread(() -> {")
        sb.appendLine("                try {")
        sb.appendLine("                    var rng = ThreadLocalRandom.current();")
        sb.appendLine("                    for (int i = 0; i < opsPerThread; i++) {")
        sb.appendLine("                        int action = rng.nextInt(${actions.size});")
        sb.appendLine("                        switch (action) {")
        for ((i, action) in actions.withIndex()) {
            val paramArgs = generateRandomParams(action, module)
            sb.appendLine("                            case $i -> ${action.name}($paramArgs);")
        }
        sb.appendLine("                        }")
        sb.appendLine("                    }")
        sb.appendLine("                } catch (Throwable e) {")
        sb.appendLine("                    errors.add(e);")
        sb.appendLine("                } finally {")
        sb.appendLine("                    latch.countDown();")
        sb.appendLine("                }")
        sb.appendLine("            }).start();")
        sb.appendLine("        }")
        sb.appendLine()
        sb.appendLine("        assertTrue(latch.await(30, TimeUnit.SECONDS), \"Timeout\");")
        sb.appendLine("        synchronized (lock) { checkInvariants(); }")
        sb.appendLine("        if (!errors.isEmpty()) {")
        sb.appendLine("            throw new AssertionError(\"Thread error: \" + errors.getFirst().getMessage(), errors.getFirst());")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine()

        sb.appendLine("}")
        sb.appendLine()

        return GeneratedTest(className, config.packageName, sb.toString(), GenerationMode.CONCURRENT)
    }

    // ─── ACTION METHOD GENERATION ────────────────────────────────────────

    private fun generateActionMethod(
        sb: StringBuilder,
        action: TlaOperatorDef,
        module: TlaModule,
        translator: JavaExprTranslator,
        config: Config
    ) {
        val params = action.params.joinToString(", ") { p ->
            "${JavaExprTranslator.typeToJava(guessParamType(p, module))} ${p.name}"
        }

        sb.appendLine("    /**")
        sb.appendLine("     * TLA+ action: ${action.name}")
        if (action.rawTla.isNotEmpty()) {
            sb.appendLine("     * ${action.rawTla.take(200).replace("\n", "\n     * ")}")
        }
        sb.appendLine("     */")
        sb.appendLine("    String ${action.name}($params) {")

        generateActionBody(sb, action.body, module, translator, config, "        ")

        sb.appendLine("    }")
        sb.appendLine()
    }

    private fun generateSynchronizedActionMethod(
        sb: StringBuilder,
        action: TlaOperatorDef,
        module: TlaModule,
        translator: JavaExprTranslator,
        config: Config
    ) {
        val params = action.params.joinToString(", ") { p ->
            "${JavaExprTranslator.typeToJava(guessParamType(p, module))} ${p.name}"
        }

        sb.appendLine("    String ${action.name}($params) {")
        sb.appendLine("        synchronized (lock) {")

        generateActionBody(sb, action.body, module, translator, config, "            ")

        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine()
    }

    private fun generateActionBody(
        sb: StringBuilder,
        body: TlaExpr,
        module: TlaModule,
        translator: JavaExprTranslator,
        config: Config,
        indent: String
    ) {
        // Decompose the action body into guard + effects
        val decomposed = decomposeAction(body, module.variables.map { it.name }.toSet())

        if (decomposed.branches.size <= 1) {
            // Single branch: guard → effects → return
            val branch = decomposed.branches.firstOrNull()
            if (branch != null && branch.guard !is TlaExpr.BoolLit) {
                sb.appendLine("${indent}if (!(${translator.translateExpr(branch.guard)})) {")
                sb.appendLine("${indent}    return \"disabled\";")
                sb.appendLine("${indent}}")
            }
            if (branch != null) {
                for (effect in branch.effects) {
                    sb.appendLine("${indent}${translateEffect(effect, translator, module)};")
                }
            }
            if (config.embedInvariants && module.invariants.isNotEmpty()) {
                sb.appendLine("${indent}checkInvariants();")
            }
            sb.appendLine("${indent}return \"ok\";")
        } else {
            // Multiple branches (disjunctive action)
            for ((i, branch) in decomposed.branches.withIndex()) {
                val keyword = if (i == 0) "if" else "} else if"
                val guardStr = if (branch.guard is TlaExpr.BoolLit && (branch.guard as TlaExpr.BoolLit).value) {
                    "true"
                } else {
                    translator.translateExpr(branch.guard)
                }
                sb.appendLine("${indent}$keyword ($guardStr) {")
                for (effect in branch.effects) {
                    sb.appendLine("${indent}    ${translateEffect(effect, translator, module)};")
                }
                if (config.embedInvariants && module.invariants.isNotEmpty()) {
                    sb.appendLine("${indent}    checkInvariants();")
                }
                sb.appendLine("${indent}    return \"${branch.label}\";")
            }
            sb.appendLine("${indent}}")
            sb.appendLine("${indent}return \"disabled\";")
        }
    }

    // ─── ACTION DECOMPOSITION ────────────────────────────────────────────

    private data class DecomposedAction(val branches: List<ActionBranch>)
    private data class ActionBranch(
        val guard: TlaExpr,
        val effects: List<ActionEffect>,
        val label: String
    )
    private data class ActionEffect(val variable: String, val expr: TlaExpr)

    private fun decomposeAction(body: TlaExpr, varNames: Set<String>): DecomposedAction {
        return when (body) {
            is TlaExpr.DisjList -> {
                val branches = body.disjuncts.mapIndexed { i, disj ->
                    decomposeConjunction(disj, varNames, "branch_$i")
                }
                DecomposedAction(branches)
            }
            is TlaExpr.ConjList -> DecomposedAction(listOf(decomposeConjunction(body, varNames, "ok")))
            else -> DecomposedAction(listOf(decomposeConjunction(body, varNames, "ok")))
        }
    }

    private fun decomposeConjunction(expr: TlaExpr, varNames: Set<String>, label: String): ActionBranch {
        val guards = mutableListOf<TlaExpr>()
        val effects = mutableListOf<ActionEffect>()

        fun processConjunct(c: TlaExpr) {
            when (c) {
                is TlaExpr.ConjList -> c.conjuncts.forEach { processConjunct(it) }
                is TlaExpr.OpApp -> {
                    if (c.op == TlaOper.EQ && c.args.size >= 2 && c.args[0] is TlaExpr.PrimedRef) {
                        // Primed assignment: var' = expr
                        val varName = (c.args[0] as TlaExpr.PrimedRef).name
                        effects.add(ActionEffect(varName, c.args[1]))
                    } else if (c.op == TlaOper.AND && c.args.size >= 2) {
                        c.args.forEach { processConjunct(it) }
                    } else if (!c.containsPrimedRefs()) {
                        guards.add(c)
                    }
                }
                is TlaExpr.Unchanged -> {
                    // No effect needed for UNCHANGED
                }
                is TlaExpr.QuantExpr -> {
                    if (expr.containsPrimedRefs()) {
                        // Inner quantifier with effects — treat whole conjunct
                        guards.add(c)
                    } else {
                        guards.add(c)
                    }
                }
                is TlaExpr.LetIn -> {
                    // LET definitions may contain effects
                    processConjunct(c.body)
                }
                else -> {
                    if (!c.containsPrimedRefs()) guards.add(c)
                }
            }
        }

        processConjunct(expr)

        val combinedGuard = when {
            guards.isEmpty() -> TlaExpr.BoolLit(true)
            guards.size == 1 -> guards[0]
            else -> TlaExpr.ConjList(guards)
        }

        return ActionBranch(combinedGuard, effects, label)
    }

    private fun translateEffect(
        effect: ActionEffect,
        translator: JavaExprTranslator,
        module: TlaModule
    ): String {
        val varType = module.variables.find { it.name == effect.variable }?.type
        val javaExpr = translator.translateExpr(effect.expr)

        // For collection types, we need deep-copy semantics
        return when {
            varType is TlaType.SetType -> {
                // Check if it's a union (add) or setminus (remove) pattern
                when (effect.expr) {
                    is TlaExpr.OpApp -> when (effect.expr.op) {
                        TlaOper.UNION -> {
                            val elemExpr = translator.translateExpr(effect.expr.args.getOrElse(1) { effect.expr })
                            "${effect.variable}.addAll($elemExpr)"
                        }
                        TlaOper.SET_MINUS -> {
                            val elemExpr = translator.translateExpr(effect.expr.args.getOrElse(1) { effect.expr })
                            "${effect.variable}.removeAll($elemExpr)"
                        }
                        else -> "${effect.variable} = new HashSet<>($javaExpr)"
                    }
                    else -> "${effect.variable} = new HashSet<>($javaExpr)"
                }
            }
            varType is TlaType.SeqType -> {
                when (effect.expr) {
                    is TlaExpr.OpApp -> when (effect.expr.op) {
                        TlaOper.APPEND -> {
                            val elemExpr = translator.translateExpr(effect.expr.args.getOrElse(1) { effect.expr })
                            "${effect.variable}.add($elemExpr)"
                        }
                        else -> "${effect.variable} = new ArrayList<>($javaExpr)"
                    }
                    else -> "${effect.variable} = new ArrayList<>($javaExpr)"
                }
            }
            varType is TlaType.FunctionType -> {
                when (effect.expr) {
                    is TlaExpr.ExceptExpr -> {
                        val updates = effect.expr.updates
                        if (updates.size == 1) {
                            val key = translator.translateExpr(updates[0].keys.getOrElse(0) { TlaExpr.IntLit(0) })
                            val value = translateExceptValue(updates[0].value, effect.variable, key, translator)
                            "${effect.variable}.put($key, $value)"
                        } else "${effect.variable} = new HashMap<>($javaExpr)"
                    }
                    else -> "${effect.variable} = new HashMap<>($javaExpr)"
                }
            }
            else -> "${effect.variable} = $javaExpr"
        }
    }

    private fun translateExceptValue(
        value: TlaExpr,
        mapName: String,
        key: String,
        translator: JavaExprTranslator
    ): String {
        // Handle @ (self-reference) in EXCEPT values: [f EXCEPT ![k] = @ + 1]
        return when (value) {
            is TlaExpr.OpApp -> when (value.op) {
                TlaOper.PLUS -> {
                    val left = value.args.getOrNull(0)
                    val right = value.args.getOrNull(1)
                    if (left is TlaExpr.AtExpr || left is TlaExpr.FunAppExpr) {
                        "$mapName.get($key) + ${translator.translateExpr(right ?: TlaExpr.IntLit(0))}"
                    } else translator.translateExpr(value)
                }
                TlaOper.MINUS -> {
                    val left = value.args.getOrNull(0)
                    val right = value.args.getOrNull(1)
                    if (left is TlaExpr.AtExpr || left is TlaExpr.FunAppExpr) {
                        "$mapName.get($key) - ${translator.translateExpr(right ?: TlaExpr.IntLit(0))}"
                    } else translator.translateExpr(value)
                }
                else -> translator.translateExpr(value)
            }
            is TlaExpr.AtExpr -> "$mapName.get($key)"
            else -> translator.translateExpr(value)
        }
    }

    // ─── INIT EXTRACTION ─────────────────────────────────────────────────

    private fun extractInitAssignments(body: TlaExpr, translator: JavaExprTranslator): List<Pair<String, String>> {
        val assignments = mutableListOf<Pair<String, String>>()

        fun process(expr: TlaExpr) {
            when (expr) {
                is TlaExpr.ConjList -> expr.conjuncts.forEach { process(it) }
                is TlaExpr.OpApp -> {
                    if (expr.op == TlaOper.EQ && expr.args.size >= 2) {
                        val varName = (expr.args[0] as? TlaExpr.NameRef)?.name
                        if (varName != null) {
                            assignments.add(varName to translator.translateExpr(expr.args[1]))
                        }
                    }
                    if (expr.op == TlaOper.AND) expr.args.forEach { process(it) }
                }
                else -> {}
            }
        }

        process(body)
        return assignments
    }

    // ─── HELPERS ─────────────────────────────────────────────────────────

    private fun buildTranslator(module: TlaModule): JavaExprTranslator {
        val vars = module.variables.associate { it.name to it.type }
        val consts = module.constants.associate { it.name to it.type }
        return JavaExprTranslator(vars, consts)
    }

    private fun guessConstantDefault(constant: TlaConstant, module: TlaModule): String {
        // Look at TypeOK for range hints, or use sensible defaults
        val typeOK = module.typeOK ?: return "5"
        return when (constant.type) {
            is TlaType.IntType, is TlaType.NatType -> "5"
            is TlaType.SetType -> "Set.of(1, 2, 3)"
            is TlaType.ModelValueType -> "5"
            else -> "5"
        }
    }

    private fun guessParamType(param: TlaFormalParam, module: TlaModule): TlaType {
        // Try to infer from Next quantifier bindings
        val next = module.next ?: return TlaType.IntType
        return findParamTypeInNext(param.name, next.body) ?: TlaType.IntType
    }

    private fun findParamTypeInNext(paramName: String, expr: TlaExpr): TlaType? {
        return when (expr) {
            is TlaExpr.QuantExpr -> {
                val bound = expr.bounds.find { it.name == paramName }
                if (bound != null) inferDomainType(bound.set)
                else findParamTypeInNext(paramName, expr.body)
            }
            is TlaExpr.DisjList -> expr.disjuncts.firstNotNullOfOrNull { findParamTypeInNext(paramName, it) }
            is TlaExpr.ConjList -> expr.conjuncts.firstNotNullOfOrNull { findParamTypeInNext(paramName, it) }
            else -> null
        }
    }

    private fun inferDomainType(domainExpr: TlaExpr): TlaType = when (domainExpr) {
        is TlaExpr.NameRef -> TlaType.IntType // Assume model values map to int
        is TlaExpr.OpApp -> when (domainExpr.op) {
            TlaOper.DOT_DOT -> TlaType.IntType
            else -> TlaType.IntType
        }
        else -> TlaType.IntType
    }

    private fun generateRandomParams(action: TlaOperatorDef, module: TlaModule): String {
        return action.params.joinToString(", ") { p ->
            val type = guessParamType(p, module)
            when (type) {
                is TlaType.IntType, is TlaType.NatType -> "rng.nextInt(1, 6)"
                is TlaType.BoolType -> "rng.nextBoolean()"
                else -> "rng.nextInt(1, 6)"
            }
        }
    }

    private fun generateDefaultParams(action: TlaOperatorDef): String {
        return action.params.joinToString(", ") { "1" }
    }

    private fun isCollectionType(type: TlaType): Boolean = when (type) {
        is TlaType.SetType, is TlaType.SeqType, is TlaType.FunctionType,
        is TlaType.TupleType, is TlaType.RecordType -> true
        else -> false
    }

    private fun escapeJavaString(s: String): String =
        s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
}
