package io.github.spec2test.generator

import io.github.spec2test.ir.*

/**
 * Generates a Java **interface** and an **abstract conformance test** from a [TlaModule].
 *
 * The interface exposes the TLA+ actions as void methods and the state variables
 * as getter methods.  The abstract test drives a developer-provided implementation
 * through random action sequences, checking TLA+ invariants after every step.
 *
 * Generated artefacts per module:
 *   1. `{Module}Spec.java`                    — the interface
 *   2. `Abstract{Module}ConformanceTest.java`  — the abstract JUnit 5 test
 */
class JavaConformanceGenerator {

    data class Config(
        val packageName: String = "io.github.spec2test.generated",
        val stepsPerTest: Int = 100,
        val numRandomTests: Int = 50
    )

    data class GeneratedFile(
        val className: String,
        val packageName: String,
        val code: String
    )

    // ─── PUBLIC API ──────────────────────────────────────────────────────

    fun generate(module: TlaModule, config: Config): List<GeneratedFile> {
        return listOf(
            generateInterface(module, config),
            generateAbstractTest(module, config)
        )
    }

    // ─── INTERFACE GENERATION ────────────────────────────────────────────

    private fun generateInterface(module: TlaModule, config: Config): GeneratedFile {
        val className = "${module.name}Spec"
        val actions = module.actions
        val sb = StringBuilder()

        sb.appendLine("package ${config.packageName};")
        sb.appendLine()
        sb.appendLine("import java.util.*;")
        sb.appendLine()
        sb.appendLine("/**")
        sb.appendLine(" * Conformance interface generated from TLA+ specification: ${module.name}")
        sb.appendLine(" *")
        sb.appendLine(" * Implement this interface to connect your production code to the")
        sb.appendLine(" * generated conformance test ({@link Abstract${module.name}ConformanceTest}).")
        sb.appendLine(" *")
        sb.appendLine(" * <p>Actions (state transitions):")
        for (action in actions) {
            sb.appendLine(" * <ul><li>{@code ${action.name}} — ${action.rawTla.take(80).replace("\n", " ")}</li></ul>")
        }
        sb.appendLine(" *")
        sb.appendLine(" * <p>Observable state:")
        for (v in module.variables) {
            sb.appendLine(" * <ul><li>{@code ${v.name}} : ${JavaExprTranslator.typeToJava(v.type)}</li></ul>")
        }
        sb.appendLine(" *")
        sb.appendLine(" * Generated by spec2test — TLA+ to Java Test Generator")
        sb.appendLine(" */")
        sb.appendLine("public interface $className {")
        sb.appendLine()

        // Action methods
        sb.appendLine("    // ── Actions ────────────────────────────────────────────────────")
        for (action in actions) {
            val params = action.params.joinToString(", ") { p ->
                "${JavaExprTranslator.typeToJava(guessParamType(p, module))} ${p.name}"
            }
            if (action.rawTla.isNotEmpty()) {
                sb.appendLine("    /** TLA+ action: ${action.name} */")
            }
            sb.appendLine("    void ${actionMethodName(action.name)}($params);")
            sb.appendLine()
        }

        // State getters
        sb.appendLine("    // ── State observation ──────────────────────────────────────────")
        for (v in module.variables) {
            val javaType = JavaExprTranslator.typeToJava(v.type)
            sb.appendLine("    /** TLA+ variable: ${v.name} */")
            sb.appendLine("    $javaType ${JavaExprTranslator.toGetterName(v.name)}();")
            sb.appendLine()
        }

        sb.appendLine("}")
        sb.appendLine()

        return GeneratedFile(className, config.packageName, sb.toString())
    }

    // ─── ABSTRACT TEST GENERATION ────────────────────────────────────────

    private fun generateAbstractTest(module: TlaModule, config: Config): GeneratedFile {
        val className = "Abstract${module.name}ConformanceTest"
        val specInterface = "${module.name}Spec"
        val actions = module.actions
        val invariants = module.invariants
        val init = module.init
        val varNames = module.variables.map { it.name }.toSet()

        // Build a translator that reads state through subject getters
        // and constants through the test's overridable getter methods
        val vars = module.variables.associate { it.name to it.type }
        val consts = module.constants.associate { it.name to it.type }
        val constNames = consts.keys
        val subjectTranslator = JavaExprTranslator(vars, consts) { name ->
            if (name in constNames) "${JavaExprTranslator.toGetterName(name)}()"
            else JavaExprTranslator.toGetterCall("subject", name)
        }
        // Plain translator for init value expressions (no subject prefix)
        val plainTranslator = JavaExprTranslator(vars, consts)

        val sb = StringBuilder()

        // Package & imports
        sb.appendLine("package ${config.packageName};")
        sb.appendLine()
        sb.appendLine("import org.junit.jupiter.api.BeforeEach;")
        sb.appendLine("import org.junit.jupiter.api.RepeatedTest;")
        sb.appendLine("import static org.junit.jupiter.api.Assertions.*;")
        sb.appendLine()
        sb.appendLine("import java.util.*;")
        sb.appendLine("import java.util.stream.*;")
        sb.appendLine("import java.util.concurrent.ThreadLocalRandom;")
        sb.appendLine()

        // Class javadoc
        sb.appendLine("/**")
        sb.appendLine(" * Abstract conformance test generated from TLA+ specification: ${module.name}")
        sb.appendLine(" *")
        sb.appendLine(" * Extend this class and implement {@link #createSubject()} to provide your")
        sb.appendLine(" * {@link $specInterface} implementation.  The test will exercise random action")
        sb.appendLine(" * sequences and verify that all TLA+ safety invariants hold after every step.")
        sb.appendLine(" *")
        sb.appendLine(" * <pre>")
        sb.appendLine(" * public class My${module.name}Test extends $className {")
        sb.appendLine(" *     {@literal @}Override")
        sb.appendLine(" *     protected $specInterface createSubject() {")
        sb.appendLine(" *         return new My${module.name}Adapter();")
        sb.appendLine(" *     }")
        sb.appendLine(" * }")
        sb.appendLine(" * </pre>")
        sb.appendLine(" *")
        sb.appendLine(" * Generated by spec2test — TLA+ to Java Test Generator")
        sb.appendLine(" *")
        sb.appendLine(" * Formal foundation:")
        sb.appendLine(" *   LTS = (S, S₀, Σ, →, Φ) where")
        sb.appendLine(" *     S  = {${module.variables.joinToString(", ") { it.name }}}")
        sb.appendLine(" *     Σ  = {${actions.joinToString(", ") { it.name }}}")
        sb.appendLine(" *     Φ  = {${invariants.joinToString(", ") { it.name }}}")
        sb.appendLine(" */")
        sb.appendLine("public abstract class $className {")
        sb.appendLine()

        // Subject field
        sb.appendLine("    protected $specInterface subject;")
        sb.appendLine()

        // Abstract factory
        sb.appendLine("    // ── Subject factory ───────────────────────────────────────────")
        sb.appendLine("    /**")
        sb.appendLine("     * Create an instance of the system under test.")
        sb.appendLine("     * Called before each test — return a fresh, initialized instance.")
        sb.appendLine("     */")
        sb.appendLine("    protected abstract $specInterface createSubject();")
        sb.appendLine()

        // Constants as overridable getters
        if (module.constants.isNotEmpty()) {
            sb.appendLine("    // ── Constants (override to customise) ──────────────────────────")
            for (c in module.constants) {
                val javaType = JavaExprTranslator.typeToJava(c.type)
                val defaultVal = guessConstantDefault(c, module)
                sb.appendLine("    /** TLA+ constant: ${c.name} (default: $defaultVal) */")
                sb.appendLine("    protected $javaType ${JavaExprTranslator.toGetterName(c.name)}() { return $defaultVal; }")
                sb.appendLine()
            }
        }

        // @BeforeEach — create subject and verify initial state
        sb.appendLine("    // ── Initialisation ────────────────────────────────────────────")
        sb.appendLine("    @BeforeEach")
        sb.appendLine("    void init() {")
        sb.appendLine("        subject = createSubject();")
        if (init != null) {
            val initAssignments = extractInitAssignments(init.body, plainTranslator)
            for ((varName, expectedValue) in initAssignments) {
                val getter = JavaExprTranslator.toGetterCall("subject", varName)
                val varType = module.variables.find { it.name == varName }?.type
                if (varType != null && isObjectType(varType)) {
                    sb.appendLine("        assertEquals($expectedValue, $getter, \"Initial state: $varName\");")
                } else {
                    sb.appendLine("        assertEquals($expectedValue, $getter, \"Initial state: $varName\");")
                }
            }
        }
        sb.appendLine("        checkInvariants();")
        sb.appendLine("    }")
        sb.appendLine()

        // Guard methods
        sb.appendLine("    // ── Guards (action preconditions) ─────────────────────────────")
        for (action in actions) {
            generateGuardMethod(sb, action, module, subjectTranslator, varNames)
        }

        // Invariant checker
        if (invariants.isNotEmpty()) {
            sb.appendLine("    // ── Safety invariants Φ ───────────────────────────────────────")
            sb.appendLine("    private void checkInvariants() {")
            for (inv in invariants) {
                val javaExpr = subjectTranslator.translateExpr(inv.body)
                sb.appendLine("        if (!($javaExpr)) {")
                sb.appendLine("            fail(\"Invariant '${inv.name}' violated: ${escapeJavaString(inv.rawTla.take(100))}\");")
                sb.appendLine("        }")
            }
            sb.appendLine("    }")
            sb.appendLine()
        }

        // Random walk conformance test
        sb.appendLine("    // ── Random walk conformance test ──────────────────────────────")
        sb.appendLine("    @RepeatedTest(${config.numRandomTests})")
        sb.appendLine("    void randomWalkConformanceTest() {")
        sb.appendLine("        var rng = ThreadLocalRandom.current();")
        sb.appendLine("        for (int step = 0; step < ${config.stepsPerTest}; step++) {")
        sb.appendLine("            int action = rng.nextInt(${actions.size});")
        sb.appendLine("            switch (action) {")
        for ((i, action) in actions.withIndex()) {
            val guardCall = "can${action.name.replaceFirstChar { it.uppercaseChar() }}"
            val paramArgs = generateRandomParams(action, module)
            val methodName = actionMethodName(action.name)
            if (action.params.isEmpty()) {
                sb.appendLine("                case $i -> { if ($guardCall()) subject.$methodName(); }")
            } else {
                // For parameterized actions: generate params, check guard, call
                sb.appendLine("                case $i -> {")
                for (p in action.params) {
                    val pType = guessParamType(p, module)
                    sb.appendLine("                    ${JavaExprTranslator.typeToJava(pType)} ${p.name} = ${generateRandomValue(pType)};")
                }
                val argList = action.params.joinToString(", ") { it.name }
                sb.appendLine("                    if ($guardCall($argList)) subject.$methodName($argList);")
                sb.appendLine("                }")
            }
        }
        sb.appendLine("            }")
        sb.appendLine("            checkInvariants();")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine()

        sb.appendLine("}")
        sb.appendLine()

        return GeneratedFile(className, config.packageName, sb.toString())
    }

    // ─── GUARD METHOD GENERATION ─────────────────────────────────────────

    private fun generateGuardMethod(
        sb: StringBuilder,
        action: TlaOperatorDef,
        module: TlaModule,
        translator: JavaExprTranslator,
        varNames: Set<String>
    ) {
        val decomposed = decomposeAction(action.body, varNames)
        val guardName = "can${action.name.replaceFirstChar { it.uppercaseChar() }}"

        val params = action.params.joinToString(", ") { p ->
            "${JavaExprTranslator.typeToJava(guessParamType(p, module))} ${p.name}"
        }

        sb.appendLine("    private boolean $guardName($params) {")

        if (decomposed.branches.size <= 1) {
            val branch = decomposed.branches.firstOrNull()
            if (branch != null && branch.guard !is TlaExpr.BoolLit) {
                sb.appendLine("        return ${translator.translateExpr(branch.guard)};")
            } else {
                sb.appendLine("        return true;")
            }
        } else {
            // Disjunctive: any branch's guard is sufficient
            val guardExprs = decomposed.branches.mapNotNull { branch ->
                if (branch.guard is TlaExpr.BoolLit && (branch.guard as TlaExpr.BoolLit).value) null
                else translator.translateExpr(branch.guard)
            }
            if (guardExprs.isEmpty()) {
                sb.appendLine("        return true;")
            } else {
                sb.appendLine("        return ${guardExprs.joinToString(" || ") { "($it)" }};")
            }
        }

        sb.appendLine("    }")
        sb.appendLine()
    }

    // ─── ACTION DECOMPOSITION (mirrored from JavaTestGenerator) ──────────

    private data class DecomposedAction(val branches: List<ActionBranch>)
    private data class ActionBranch(val guard: TlaExpr, val effects: List<ActionEffect>, val label: String)
    private data class ActionEffect(val variable: String, val expr: TlaExpr)

    private fun decomposeAction(body: TlaExpr, varNames: Set<String>): DecomposedAction {
        return when (body) {
            is TlaExpr.DisjList -> {
                val branches = body.disjuncts.mapIndexed { i, disj ->
                    decomposeConjunction(disj, varNames, "branch_$i")
                }
                DecomposedAction(branches)
            }
            is TlaExpr.ConjList -> DecomposedAction(listOf(decomposeConjunction(body, varNames, "ok")))
            else -> DecomposedAction(listOf(decomposeConjunction(body, varNames, "ok")))
        }
    }

    private fun decomposeConjunction(expr: TlaExpr, varNames: Set<String>, label: String): ActionBranch {
        val guards = mutableListOf<TlaExpr>()
        val effects = mutableListOf<ActionEffect>()

        fun processConjunct(c: TlaExpr) {
            when (c) {
                is TlaExpr.ConjList -> c.conjuncts.forEach { processConjunct(it) }
                is TlaExpr.OpApp -> {
                    if (c.op == TlaOper.EQ && c.args.size >= 2 && c.args[0] is TlaExpr.PrimedRef) {
                        val varName = (c.args[0] as TlaExpr.PrimedRef).name
                        effects.add(ActionEffect(varName, c.args[1]))
                    } else if (c.op == TlaOper.AND && c.args.size >= 2) {
                        c.args.forEach { processConjunct(it) }
                    } else if (!c.containsPrimedRefs()) {
                        guards.add(c)
                    }
                }
                is TlaExpr.Unchanged -> { /* no guard contribution */ }
                is TlaExpr.QuantExpr -> guards.add(c)
                is TlaExpr.LetIn -> processConjunct(c.body)
                else -> {
                    if (!c.containsPrimedRefs()) guards.add(c)
                }
            }
        }

        processConjunct(expr)

        val combinedGuard = when {
            guards.isEmpty() -> TlaExpr.BoolLit(true)
            guards.size == 1 -> guards[0]
            else -> TlaExpr.ConjList(guards)
        }

        return ActionBranch(combinedGuard, effects, label)
    }

    // ─── INIT EXTRACTION ─────────────────────────────────────────────────

    private fun extractInitAssignments(
        body: TlaExpr,
        translator: JavaExprTranslator
    ): List<Pair<String, String>> {
        val assignments = mutableListOf<Pair<String, String>>()

        fun process(expr: TlaExpr) {
            when (expr) {
                is TlaExpr.ConjList -> expr.conjuncts.forEach { process(it) }
                is TlaExpr.OpApp -> {
                    if (expr.op == TlaOper.EQ && expr.args.size >= 2) {
                        val varName = (expr.args[0] as? TlaExpr.NameRef)?.name
                        if (varName != null) {
                            assignments.add(varName to translator.translateExpr(expr.args[1]))
                        }
                    }
                    if (expr.op == TlaOper.AND) expr.args.forEach { process(it) }
                }
                else -> {}
            }
        }

        process(body)
        return assignments
    }

    // ─── HELPERS ─────────────────────────────────────────────────────────

    private fun actionMethodName(tlaName: String): String =
        tlaName.replaceFirstChar { it.lowercaseChar() }

    private fun guessConstantDefault(constant: TlaConstant, module: TlaModule): String {
        return when (constant.type) {
            is TlaType.IntType, is TlaType.NatType -> "5"
            is TlaType.SetType -> "Set.of(1, 2, 3)"
            is TlaType.ModelValueType -> "5"
            else -> "5"
        }
    }

    private fun guessParamType(param: TlaFormalParam, module: TlaModule): TlaType {
        val next = module.next ?: return TlaType.IntType
        return findParamTypeInNext(param.name, next.body) ?: TlaType.IntType
    }

    private fun findParamTypeInNext(paramName: String, expr: TlaExpr): TlaType? {
        return when (expr) {
            is TlaExpr.QuantExpr -> {
                val bound = expr.bounds.find { it.name == paramName }
                if (bound != null) TlaType.IntType
                else findParamTypeInNext(paramName, expr.body)
            }
            is TlaExpr.DisjList -> expr.disjuncts.firstNotNullOfOrNull { findParamTypeInNext(paramName, it) }
            is TlaExpr.ConjList -> expr.conjuncts.firstNotNullOfOrNull { findParamTypeInNext(paramName, it) }
            else -> null
        }
    }

    private fun generateRandomParams(action: TlaOperatorDef, module: TlaModule): String {
        return action.params.joinToString(", ") { p ->
            generateRandomValue(guessParamType(p, module))
        }
    }

    private fun generateRandomValue(type: TlaType): String = when (type) {
        is TlaType.IntType, is TlaType.NatType -> "rng.nextInt(1, 6)"
        is TlaType.BoolType -> "rng.nextBoolean()"
        else -> "rng.nextInt(1, 6)"
    }

    private fun isObjectType(type: TlaType): Boolean = when (type) {
        is TlaType.IntType, is TlaType.NatType, is TlaType.BoolType, is TlaType.IntervalType -> false
        else -> true
    }

    private fun escapeJavaString(s: String): String =
        s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
}
